### ISSUE TITLE
Error: There is already a collection named "ostrioMongoLogger"

### ISSUE THREAD

**Issue by mklueh** [VeliovGroup/Meteor-logger-mongo#22] opened 2018-01-13 11:31 UTC
Where should I do the enable call/initialization?

I was trying to put

```
import {Logger} from 'meteor/ostrio:logger';
import { LoggerMongo } from 'meteor/ostrio:loggermongo';
const log = new Logger();
new LoggerMongo(log).enable();
```

in every file I´m planning to use the logger, which doesn´t work and throws

> Error: There is already a collection named "ostrioMongoLogger"

Do I need to create a global logger instance and pass it into every subclass instead or what is the prefered way to go?

**Comment by dr-dimitru** [comment] 2018-01-13 11:56
Hello @Mklueh ,

Yes, logger should be created (*initialized*) once, and then imported everywhere it needed, or as globally available variable.

To create multiple instances or to use Mongo collection of your choice, use:
 - `options.collection` {*Mongo.Collection*} - Use to pass your own MongoDB collection instance, {*Mongo.Collection*} returned from new `Mongo.Collection()`
 - `options.collectionName` {*String*} - MongoDB collection name, default: `ostrioMongoLogger`
 - Note: You can't pass both `collection` and `collectionName` simultaneously. Set only one of those options. If both options is presented `collection` is more prioritized

As stated in a [docs](https://github.com/VeliovGroup/Meteor-logger-mongo#initialization-isomorphic)

**Comment by dr-dimitru** [comment] 2018-01-18 02:58
Hello @Mklueh ,

Have you solved this one?
Feel free to close it in case if the issue is solved on your end.
//cc @mksh-su

**Comment by dr-dimitru** [comment] 2018-07-27 00:24
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.

**Closed as completed by dr-dimitru** 2018-07-27 00:24 UTC
Labels: question
